import {StyleSheet} from 'react-native';
import NotoSansRegular from './assets/fonts/NotoSans-Regular.ttf';
import NotoSansBold from './assets/fonts/NotoSans-Bold.ttf';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#D6EFE7',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  topSection: {
    height: 260,
    width: 200,
  },
  image: {
    height: 230,
    width: 230,
  },
  bgText: {
    position: 'absolute',
    bottom: -10,
    left: 20,
    color: '#02111A',
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 20,
    width: 160,
    fontFamily: 'NotoSansBold',
  },
  bottomSection: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 600,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: -2},
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 2,
    flexShrink: 0,
    paddingLeft: 16,
    paddingRight: 16,
  },
  headline: {
    fontWeight: '600',
    fontFamily: 'NotoSansBold',
    color: '#02111A',
    fontSize: 22,
    marginTop: 2,
    marginBottom: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  subTitle: {
    color: '#4E585E',
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 20,
    width: 240,
    marginBottom: 8,
    fontFamily: 'NotoSansRegular',
  },
  fullWidthButton: {
    height: 52,
    width: '100%',
    marginTop: 6,
  },
  fullWidthButtonText: {
    width: '100%',
    height: 54,
    marginTop: 6,
    fontSize: 16,
    fontWeight: '600',
    color: 'white',
    backgroundColor: '#30AF89',
    borderRadius: 6,
    padding: 14,
    textAlign: 'center',
  },
});
